[package]
name = "gps"
version = "5.2.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
structopt = "0.3.26"
regex = "1.5.6"
lazy_static = "1.4.0"
is_executable = "1.0.1"
home-dir = "0.1.0"
gpgme = "0.10.0"
toml = "0.5.9"
ansi_term = "0.12.1"
ureq = "2.4.0"
version-compare = "0.1.0"

[patch.crates-io]
home-dir = { git = 'https://github.com/uptech/home-dir', branch = 'upgrade-nix-dependency-to-latest' }

[dev-dependencies]
tempfile = "3.2.0"

[build-dependencies]
structopt = "0.3.26"
